name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy==1.24.4
    - gym==0.22.0
    - mujoco-py==2.1.2.14
    - matplotlib==3.7.5
    - torch==2.3.0+cu111
    - typed-argument-parser=1.10.0
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython==3.1.43
    - einops==0.8.0
    - ffmpeg==4.2.2
    - ffprobe
    - pillow==7.2.0
    - tqdm==4.66.2
    - pandas==2.0.3
    - wandb
    - flax >= 0.3.5
    - jax <= 0.2.21
    - ray==2.0.0
    - ray==2.0.0
    - crcmod 
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown==2.3.1
    - stable-baselines3==2.3.2
    - jupyterlab==4.0.11
    - pytorch==2.3.0
    - torchvision==0.18.0
    - torchaudio==2.3.0
    - mjrl==1.0.0
    - scipy==1.10.1
    - seaborn==0.13.2

